/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package correo;

import Conteiner.Menu;
import java.awt.Color;
import java.awt.Image;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/**
 *
 * @author eloy2311
 */
public class Enviar extends javax.swing.JFrame {

    /**
     * Creates new form Enviar
     */
    
    
    
    corre c = new corre();
    
    public Enviar() {
        initComponents();
         this.setLocationRelativeTo(null);
         Color colorFondo=new Color(174,203,243 );
         this.getContentPane().setBackground(colorFondo);
        CargarCB();
    }
    
    public void enviarmail(){
        c.setPass("Marthadominguez2");
        c.setUser("eloym2311@gmail.com");
        c.setAsunto(asunto.getText());
        c.setDestino(correo.getSelectedItem().toString());
        c.setMensaje(mensaje.getText());
        c.setFilename("Hoja de Servicio.pdf");
        c.setRuta(image1.getText());
        
        Controlador co = new Controlador();
        
        
       // co.sendmail(c);
        
         if(co.sendmail(c)){
             JOptionPane.showMessageDialog(null, "Envio correcto");
         }else{
             JOptionPane.showMessageDialog(null, "envio correcto");
            }
    }
    
    public void CargarCB(){
   Conectar1 cc = new Conectar1();
    Connection cn = cc.conexion();
    String cap="";
        String sql="SELECT * FROM cliente";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            correo.removeAllItems();
            correo.addItem("Select..");
          
            while(rs.next()){
                 correo.addItem(rs.getString("correo"));
            }
    
    
}    catch (SQLException ex) {   
         Logger.getLogger(Enviar.class.getName()).log(Level.SEVERE, null, ex);
     }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        asunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        fotoL = new javax.swing.JButton();
        image1 = new javax.swing.JTextField();
        correo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Destino");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 35, 80, 30));

        jLabel2.setText("Asunto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 64, 80, 30));

        asunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuntoActionPerformed(evt);
            }
        });
        getContentPane().add(asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 290, 30));

        mensaje.setColumns(20);
        mensaje.setRows(5);
        jScrollPane1.setViewportView(mensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 530, 280));

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 110, 30));

        fotoL.setText("Seleccionar Archivo");
        fotoL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fotoLMouseClicked(evt);
            }
        });
        getContentPane().add(fotoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 170, 40));
        getContentPane().add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 370, 40));

        correo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 290, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuntoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        enviarmail();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fotoLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotoLMouseClicked
        // TODO add your handling code here:
                JFileChooser archivo = new JFileChooser();
        int window = archivo.showOpenDialog(null);
        if(window==JFileChooser.APPROVE_OPTION){
            File file= archivo.getSelectedFile();
            image1.setText(String.valueOf(file));
            Image foto =getToolkit().getImage(image1.getText()).getScaledInstance(150,150, Image.SCALE_DEFAULT);
            fotoL.setIcon(new ImageIcon(foto));
            this.repaint();
        }
    }//GEN-LAST:event_fotoLMouseClicked

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     Menu x = new Menu();
      x.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enviar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Enviar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asunto;
    private javax.swing.JComboBox<String> correo;
    private javax.swing.JButton fotoL;
    private javax.swing.JTextField image1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensaje;
    // End of variables declaration//GEN-END:variables
}
