package Conteiner;


import java.awt.Color;
import java.security.Principal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eloy2311
 */
public class Equipo extends javax.swing.JFrame {
        Connection con=null;
    Statement stmt=null; 
      ResultSet rs=null;
    /**
     * Creates new form Equipo
     */
    public Equipo() {
        initComponents();
        num();
          this.setLocationRelativeTo(null);
         Color colorFondo=new Color(174,203,243 );
         this.getContentPane().setBackground(colorFondo);
    }

    
      public void num(){
            try {
                String k="";
                int x;
                String z="";
                
                String url="jdbc:mysql://localhost:3306/prueba";
                String usuario="root";
                String contraseña="";
                
                try {
                    Class.forName("com.mysql.jdbc.Driver").newInstance();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
                }
                con = DriverManager.getConnection(url,usuario,contraseña);
                if ( con != null )
                    System.out.println("Se ha establecido una conexión a la base de datos " +
                            "\n " + url );
                
                
                String sql="SELECT MAX(id) AS id FROM cliente";
                
                try{
                    
                    stmt=con.createStatement();
                    rs=stmt.executeQuery(sql);
                    
                    if (rs.next()){
                        
                        k=rs.getString("id");
                        x=Integer.parseInt(k);
                        
                        z=String.valueOf(x);
                        // c=rs.getString("id_invoice");
                        System.out.println(x);
                        
                        clienteid.setText(z);
                        
                    }
                    
                }catch (Exception e){}
            } catch (SQLException ex) {
                Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
            }
              }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        equi = new javax.swing.JTextField();
        mark = new javax.swing.JTextField();
        mod = new javax.swing.JTextField();
        serie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        clienteid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Datos del Equipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 43, 223, 23));

        jLabel2.setText("Marca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 218, 109, 39));

        jLabel3.setText("Modelo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 289, 109, 39));

        jLabel4.setText("Numero de Serie");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 346, 109, 39));

        jLabel5.setText("Equipo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 173, 109, 39));
        getContentPane().add(equi, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 162, 180, 40));

        mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markActionPerformed(evt);
            }
        });
        getContentPane().add(mark, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 180, 40));
        getContentPane().add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 180, 40));
        getContentPane().add(serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 335, 180, 40));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        jLabel6.setText("Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 80, 30));

        clienteid.setEditable(false);
        clienteid.setEnabled(false);
        clienteid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteidActionPerformed(evt);
            }
        });
        getContentPane().add(clienteid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 180, 30));

        jButton3.setText("Impimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_markActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String equipo, modelo, marca, numseria,idclie;
        
        equipo = equi.getText().toString();
        marca = mark.getText().toString();
        modelo = mod.getText().toString();
        numseria = serie.getText().toString();
        idclie = clienteid.getText().toString();
        
        int id = Integer.parseInt(idclie);
        
        if(  equi.getText().equals("") || mark.getText().equals("") ||  mod.getText().equals("") ||  serie.getText().equals("")){
             javax.swing.JOptionPane.showMessageDialog(this,"Debes llenar los campos \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
                    try{
        
//            String url="jdbc:mysql://sql12.freesqldatabase.com:3306/sql12221227";
//            String usuario="sql12221227";
//            String contraseña= "w4iMpnC4kL";
String url="jdbc:mysql://localhost:3306/prueba";
String usuario="root";
String contraseña="";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
         stmt = con.createStatement(); 
          stmt.executeUpdate("INSERT INTO equipo VALUES('" + 0 + "','"+equipo+"','"+marca+"','"+modelo+"','"+numseria+"','"+id+"')");
          System.out.println("Los valores han sido agregados a la base de datos ");
         } catch (SQLException ex) {
                Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE, null, ex);
            }    
            finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
            
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
         Actividades x = new Actividades();
         x.setVisible(true);
         this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clienteidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JasperReport report;
        
        String path = "C:\\PruebaReporte\\src\\pruebareporte\\Reporte\\invoice.jasper";
        try{
            report = (JasperReport)JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path,null,cn);
            JasperViewer viewer = new JasperViewer(jprint,false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
Conectar cc = new Conectar();
    Connection cn = cc.conexion();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clienteid;
    private javax.swing.JTextField equi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mark;
    private javax.swing.JTextField mod;
    private javax.swing.JTextField serie;
    // End of variables declaration//GEN-END:variables
}
