package Conteiner;


import correo.Enviar;
import ds.desktop.notify.DesktopNotify;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.print.attribute.standard.DateTimeAtCompleted;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eloy2311
 */
public class Menu extends javax.swing.JFrame {
 Conectar cc = new Conectar();
    Connection cn = cc.conexion();
  Connection con=null;
    Statement stmt=null; 
      ResultSet rs=null;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
         this.setLocationRelativeTo(null);
         Color colorFondo=new Color(174,203,243 );
         this.getContentPane().setBackground(colorFondo);
         
         button();
         alerta();
         
    }
    void button(){
        start.setOpaque(false);
        start.setContentAreaFilled(false);
        start.setBorderPainted(false);   
        
        salida.setOpaque(false);
        salida.setContentAreaFilled(false);
        salida.setBorderPainted(false);   
        
        enviar.setOpaque(false);
        enviar.setContentAreaFilled(false);
        enviar.setBorderPainted(false);   
        
        wisp.setOpaque(false);
        wisp.setContentAreaFilled(false);
        wisp.setBorderPainted(false);
    }
    
    
    public void alerta(){
        String fechaentrada;
        Date fechadeberia;
        String idcl;
         String cap="";
        String sql="SELECT * FROM obseentrada";
       
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
          
            while(rs.next()){
            fechaentrada = rs.getString(1);
            idcl = rs.getString(2);
            //System.out.println(fechaentrada);
             Date now = new Date(System.currentTimeMillis());
SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            
   /* Date now = new Date(System.currentTimeMillis());        
  SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
Date fecha = null;
try {
fecha =   formato.parse(fechaentrada);
} catch (ParseException ex) {
ex.printStackTrace();
}
System.out.println(fecha.toString());
     */          String today = date.format(now);
                //System.out.println( date.format(now));    
             //   System.out.println(today);
    
                if(today == fechaentrada){
                  DesktopNotify.showDesktopMessage(
               "Alerta",
                       "La orden de servicio del cliente  "+idcl+" esta retrasada",
                       DesktopNotify.WARNING
               
               );
                }
              
            }
    
    
}    catch (SQLException ex) {   
         Logger.getLogger(salida.class.getName()).log(Level.SEVERE, null, ex);
     }   
       
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        salida = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        wisp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/invoice3.png"))); // NOI18N
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 180, 190));

        salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/datos de salida.png"))); // NOI18N
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        getContentPane().add(salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 180, 190));

        enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/send.png"))); // NOI18N
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 180, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/esquina menu.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 230, 230));

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, -1));

        wisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wisp11.png"))); // NOI18N
        wisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wispActionPerformed(evt);
            }
        });
        getContentPane().add(wisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 190, 210));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLIENTES WISP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 150, 20));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATOS DE SALIDA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 150, 20));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ENVIAR ORDENES DE SERVICIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 180, 20));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ORDENES DE SERVICIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 20));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        // TODO add your handling code here:}
        salida x = new salida();
        x.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_salidaActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        Llenado x = new Llenado();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        
        Enviar x = new Enviar();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_enviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      Login x = new Login();
      x.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void wispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wispActionPerformed
        // TODO add your handling code here:
        Wisp x = new Wisp();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wispActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton salida;
    private javax.swing.JButton start;
    private javax.swing.JButton wisp;
    // End of variables declaration//GEN-END:variables
}
