package Conteiner;


import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author eloy2311
 */
public class RegistroUser extends javax.swing.JFrame {

    /**
     * Creates new form RegistroUser
     */
     Connection con=null;
    Statement stmt=null;    
    public RegistroUser() {
        initComponents();
         Color colorFondo=new Color(174,203,243 );
         this.getContentPane().setBackground(colorFondo);
          this.setLocationRelativeTo(null);
    }
    
    
    
     public boolean isEmail(String mail){
      Pattern pat = null;
Matcher mat = null;
pat = Pattern.compile("^([0-9a-zA-Z]([_.w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-w]*[0-9a-zA-Z].)+([a-zA-Z]{2,9}.)+[a-zA-Z]{2,3})$");
mat = pat.matcher(mail);
if (mat.find()) {
System.out.println("[" + mat.group() + "]");
return true;
}else{
return false;
}
}
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        nick = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pass2 = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel2.setText("Telefono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 120, 40));

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 40));

        jLabel4.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel4.setText("Nick Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 40));

        jLabel5.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 120, 40));

        jLabel6.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 120, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/understandable.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 270, 230));

        tipo.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Manager", "Empleado" }));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 200, 40));

        jLabel8.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de Usuario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, 120, 40));

        name.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 200, 40));

        tel.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 40));

        nick.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        nick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nickKeyTyped(evt);
            }
        });
        getContentPane().add(nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 200, 40));

        mail.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 200, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 733, 170, 50));

        pass2.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        pass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass2KeyTyped(evt);
            }
        });
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 200, 40));

        pass.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 200, 40));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 815));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           String name1, tel1, nick1, pass1,email1, tipo1;
        name1 = name.getText().toString();
        tel1 = tel.getText().toString();
        nick1 = nick.getText().toString();
        pass1 = pass.getText().toString();
        email1 = mail.getText().toString();
        tipo1 = tipo.getSelectedItem().toString();
    
        
        
       if( name.getText().equals("") ||  nick.getText().equals("") || pass.getText().equals("") 
               || mail.getText().equals("") ){
           javax.swing.JOptionPane.showMessageDialog(this,"Debes llenar los campos \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }else{
          if(!pass.getText().equals(pass2.getText())){
            javax.swing.JOptionPane.showMessageDialog(this,"Revisa tu Contraseña \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);  
          }else{
                    try{
        
//            String url="jdbc:mysql://sql12.freesqldatabase.com:3306/sql12221227";
//            String usuario="sql12221227";
//            String contraseña= "w4iMpnC4kL";
String url="jdbc:mysql://localhost:3306/prueba";
String usuario="root";
String contraseña="";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
         stmt = con.createStatement(); 
          stmt.executeUpdate("INSERT INTO usuarios VALUES('" + 0 + "','"+name1+"','"+tel1+"','"+nick1+"','"+pass1+"','"+email1+"','"+tipo1+"')");
          System.out.println("Los valores han sido agregados a la base de datos ");
           javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           Login x = new Login();
           x.setVisible(true);
           this.dispose();
         } catch (SQLException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            }
       
            finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
            
        }
       }
        

       } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login x = new Login();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if(  name.getText().length()>=25)evt.consume();
if((car<'a' || car>'z') && (car<'A' || car>'Z')&&(car<' '||car>' ')) evt.consume();
    }//GEN-LAST:event_nameKeyTyped

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
         if(  tel.getText().length()>=10)evt.consume();
if((car<'0' || car>'9')&&(car<'.'||car>'.')) evt.consume();
       
    }//GEN-LAST:event_telKeyTyped

    private void nickKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nickKeyTyped
        // TODO add your handling code here:
         if(  nick.getText().length()>=10)evt.consume();
    }//GEN-LAST:event_nickKeyTyped

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        // TODO add your handling code here:
         if(  pass.getText().length()>=25)evt.consume();
    }//GEN-LAST:event_passKeyTyped

    private void pass2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass2KeyTyped
        // TODO add your handling code here:
         if(  pass2.getText().length()>=25)evt.consume();
    }//GEN-LAST:event_pass2KeyTyped

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        // TODO add your handling code here:
        String correo = mail.getText();

if(isEmail(correo)){
System.out.println("Mail correcto");
}else{
    JOptionPane.showMessageDialog(rootPane, "Correo no verificado");
}
    }//GEN-LAST:event_mailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nick;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
