/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conteiner;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eloy2311
 */
public class Wisp extends javax.swing.JFrame {

    
    // Connection con=null;
  //  Statement stmt=null;  
    
    Connection con=null;
  Statement stmt=null;    

 CallableStatement cts;
   ResultSet r;
   Connection cn;
   Conectar conectar=new Conectar();
    /**
     * Creates new form Wisp
     */
    public Wisp() {
        initComponents();
         this.setLocationRelativeTo(null);
         Color colorFondo=new Color(174,203,243 );
         this.getContentPane().setBackground(colorFondo);
          cn=conectar.conexion();
    }
    
    
    public void clean(){
        nombre.setText("");
        zona.setText("");
        corte.setText("");
        telf.setText("");
        dire.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        zona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        corte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dire = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 700));
        setPreferredSize(new java.awt.Dimension(742, 709));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setText("Num. de Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 130, 30));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 496, -1, -1));

        code.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        code.setEnabled(false);
        getContentPane().add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 240, 30));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setText("Zona");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 130, 30));

        zona.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(zona, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 240, 30));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setText("Corte de Servicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, 30));

        corte.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(corte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 240, 30));

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 130, 30));

        telf.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(telf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 240, 30));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setText("Direccion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 130, 30));

        dire.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 240, 30));

        jButton2.setText("CLIENTES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jButton3.setText("ATRAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 130, 30));

        nombre.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 240, 30));

        jButton6.setText("ELIMINIAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
          String name1,zona1,corte1,telf1,dirrecc;
    name1 = nombre.getText();
    zona1 = zona.getText();
    corte1 = corte.getText();
    telf1= telf.getText();
    dirrecc= dire.getText();
    
    if( nombre.getText().equals("") ||  zona.getText().equals("") || telf.getText().equals("") 
               || dire.getText().equals("")){
           javax.swing.JOptionPane.showMessageDialog(this,"Debes llenar los campos \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }else{
          
                    try{
        
//            String url="jdbc:mysql://sql12.freesqldatabase.com:3306/sql12221227";
//            String usuario="sql12221227";
//            String contraseña= "w4iMpnC4kL";
String url="jdbc:mysql://localhost:3306/prueba";
String usuario="root";
String contraseña="";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
         stmt = con.createStatement(); 
          stmt.executeUpdate("INSERT INTO wisp VALUES('" + 0 + "','"+name1+"','"+zona1+"','"+corte1+"','"+telf1+"','"+dirrecc+"')");
          System.out.println("Los valores han sido agregados a la base de datos ");
         } catch (SQLException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            }    
            finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
            
        }
                    clean();
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           
       } 
    
          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Tabla x = new Tabla();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         Menu x = new Menu();
         x.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
          String cod=JOptionPane.showInputDialog("Escribe El Número Del Cliente");
          String   sql="SELECT * FROM wisp WHERE id_wisp='"+cod+"'"; 
        try {
              Statement  st = cn.createStatement();
            ResultSet r= st.executeQuery(sql);

            if(r.next()){
            JOptionPane.showMessageDialog(this,"Cliente Encontrado!!","NOTICE",JOptionPane.INFORMATION_MESSAGE);
            this.code.setText(r.getString(1));
            this.nombre.setText(r.getString(2));
            this.zona.setText(r.getString(3));
            this.corte.setText(r.getString(4).toString());
            this.telf.setText(r.getString(5));
            this.dire.setText(r.getString(6));
            
   
            }else{

           JOptionPane.showMessageDialog(this,"Cliente no Encontrado!!","NOTICE",JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (SQLException | HeadlessException e) {JOptionPane.showMessageDialog(this, e.toString());
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        
          String name1,zona1,corte1,telf1,dirrecc, code1;
    code1 = code.getText();
    name1 = nombre.getText();
    zona1 = zona.getText();
    corte1 = corte.getText();
    telf1= telf.getText();
    dirrecc= dire.getText();
    
    if( nombre.getText().equals("") ||  zona.getText().equals("") || telf.getText().equals("") 
               || dire.getText().equals("")){
           javax.swing.JOptionPane.showMessageDialog(this,"Debes llenar los campos \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }else{
          
                    try{
        
//            String url="jdbc:mysql://sql12.freesqldatabase.com:3306/sql12221227";
//            String usuario="sql12221227";
//            String contraseña= "w4iMpnC4kL";
String url="jdbc:mysql://localhost:3306/prueba";
String usuario="root";
String contraseña="";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
         stmt = con.createStatement(); 
          stmt.executeUpdate("UPDATE wisp SET nombre='"+name1+"',zona='"+zona1+"',corte_ser='"+corte1+"',tel='"+telf1+"',direccion='"+dirrecc+"' where id_wisp='"+code1+"'");
          System.out.println("Los valores han sido agregados a la base de datos ");
         } catch (SQLException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Llenado.class.getName()).log(Level.SEVERE, null, ex);
            }    
            finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
            
        }
                    clean();
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           
       } 
    
          
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String cadena1;
        
        cadena1= code.getText();
        int conf=JOptionPane.showConfirmDialog(rootPane,"Are you sure?");
        if(conf==JOptionPane.YES_OPTION){
        try{
//             String url="jdbc:mysql://sql12.freesqldatabase.com:3306/sql12221227";
//            String usuario="sql12221227";
//            String contraseña= "w4iMpnC4kL";
String url="jdbc:mysql://localhost:3306/prueba";
String usuario="root";
String contraseña="";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             cn = DriverManager.getConnection(url,usuario,contraseña); 
             if ( cn != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
             
             stmt = cn.createStatement(); 
                  stmt.executeUpdate("DELETE FROM wisp WHERE wisp.id_wisp='"+cadena1+"'");
                  System.out.println("Los valores han sido eliminados a la base de datos ");
                   JOptionPane.showMessageDialog(this, "Product Delete", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
                
                   
          
             
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Wisp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Wisp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(Wisp.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(Wisp.class.getName()).log(Level.SEVERE, null, ex);
    }
        finally {
            if (cn != null) {
                try {
                    cn.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
            
        }
        clean();
         javax.swing.JOptionPane.showMessageDialog(this,"Update Done! \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showConfirmDialog(rootPane,"Back to the menu");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wisp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JTextField corte;
    private javax.swing.JTextField dire;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telf;
    private javax.swing.JTextField zona;
    // End of variables declaration//GEN-END:variables
}
