package usuarios;


import Interfaz.Interfaz;
import Man.Man;
import conexion.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Eloy
  * @param frame
 */
public class usuarios extends javax.swing.JFrame {
 Connection con=null;
  Statement stmt=null;
  Interfaz frame;

    /**
     * Creates new form usuarios
     */
    public usuarios(/*Interfaz frame*/) {
       // this.frame = frame;
        
        initComponents();
        CargarCB();
         this.setLocationRelativeTo(null);
    }
public void CargarCB(){
   Conexion cc = new Conexion();
    Connection cn = cc.conexion();
    String cap="";
        String sql="SELECT * FROM employees";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            empleado.removeAllItems();
            empleado.addItem("Select..");
          
            while(rs.next()){
                 empleado.addItem(rs.getString("name"));
            }
    
    
}    catch (SQLException ex) {   
         Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
     }   
        
    }
    

    

    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jlabel21 = new javax.swing.JLabel();
        nick = new javax.swing.JTextField();
        jlabel22 = new javax.swing.JLabel();
        jlabel23 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        registro = new javax.swing.JButton();
        back = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        empleado = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Empleado", "Manager" }));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 110, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 90, 30));

        jlabel21.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jlabel21.setText("Tipo de Usuario :");
        getContentPane().add(jlabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 30));

        nick.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        getContentPane().add(nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, 40));

        jlabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jlabel22.setText("Password :");
        getContentPane().add(jlabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, 30));

        jlabel23.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jlabel23.setText("Nick :");
        getContentPane().add(jlabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        password.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, 40));

        registro.setBackground(new java.awt.Color(0, 204, 204));
        registro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registro.setText("Register");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 110, 30));

        back.setBackground(new java.awt.Color(0, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 100, 30));

        salir.setBackground(new java.awt.Color(0, 204, 204));
        salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salir.setText("EXIT");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 60, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 30, 30));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, 30));

        getContentPane().add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/interfaz.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        // TODO add your handling code here:
        String cadena3,cadena4,cadena5;
        int cadena2;
        cadena2 = empleado.getSelectedIndex();
        cadena3 = password.getText().toString();
        cadena4 = nick.getText();
        cadena5 = tipo.getSelectedItem().toString();
         
        

        if (empleado.getSelectedItem().equals(null) || (password.getText().equals("")) || (nick.getText().equals("")) || (tipo.getSelectedItem().equals(null))) {

            javax.swing.JOptionPane.showMessageDialog(this,"You must to write on all the fields \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
           // name.requestFocus();
        }
        else{
            try{
        
            String url="jdbc:mysql://sql12.freesqldatabase.com:3306/sql12221227";
            String usuario="sql12221227";
            String contraseña= "w4iMpnC4kL";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexión a la base de datos " +  
                                       "\n " + url ); 
  
                  stmt = con.createStatement(); 
                  stmt.executeUpdate("INSERT INTO user VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                 
             
            } catch (SQLException ex) {
                Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
       finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( Exception e ) { 
                         System.out.println( e.getMessage());
                }
            }
            
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Register Done! \n","NOTICE!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
   
       
        this.password.setText("");
        this.nick.setText("");
        this.empleado.setSelectedIndex(0);

      


    }//GEN-LAST:event_registroActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);
               JOptionPane.showMessageDialog(null, "Now you are register");
               Interfaz ingresos1 = new Interfaz();
               ingresos1.setVisible(true);
               ingresos1.pack();
               this.dispose();

    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> empleado;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlabel21;
    private javax.swing.JLabel jlabel22;
    private javax.swing.JLabel jlabel23;
    private javax.swing.JTextField nick;
    private javax.swing.JTextField password;
    private javax.swing.JButton registro;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
